version: '3.2'
services:
  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://xdc.tenforce.com/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data

  links-scraper:
    build: .
    links:
      - db:database
    ports:
      - "8891:3000"
    volumes:
      - ./scraper-data:/data
